### ISSUE TITLE
tflite_example failed to build - tflite_runtime-2.1.0.post1-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by nullbyte91** [toradex/torizon-samples#2]
Hi Team,

I'm building tflite_example docker image for iMX8 Apalis device. I'm getting the below error,
```
ERROR: tflite_runtime-2.1.0.post1-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.
```

May I know supported wheel file for this hardware?

-
Jegathesan S

**Comment by sergioprado** [comment]
Hi Jegathesan,

Would you please open a support request in https://www.toradex.com/community/smart-spaces/72/torizon.html?

Thanks!

**Comment by leograba** [comment]
Since this bug was opened, the method to install tflite was updated, so it does not hardcode the version, on the commit https://github.com/toradex/torizon-samples/commit/cb50cf532ce29d463ebf38e591928e7318d4ad5f

Since then, our CI script did build the sample for Armv8 (Apalis iMX8) successfully.

Thus I'm closing this request. Please submit a new one if needed.
